version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - "80:80"
    environment:
    - DB_CONNECTION=mongodb
    - DB_HOST=mongodb
    - DB_PORT=27017
    - DB_DATABASE=mydatabase
    - DB_USERNAME=root
    - DB_PASSWORD=root
    volumes:
      - .:/var/www/html
    depends_on:
    - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
